### ISSUE TITLE
unexpected argument --workspace

### ISSUE THREAD

**Issue by mdsohelmia** [zed-industries/create-gpui-app#12]
create-gpui-app --workspace --name my-app
error: unexpected argument '--workspace' found

Usage: create-gpui-app [OPTIONS]

For more information, try '--help'.

**Comment by swaptr** [comment]
If you installed this crate from the registry, the error is due to needing a package update. Once updated, it should be fixed. Meanwhile, to use the latest changes, you can:
1. Clone this repository and cd into it.
2. Install this repository using the following command:
```sh
cargo install --path .
```
