### ISSUE TITLE
create project failed

### ISSUE THREAD

**Issue by wzzc-dev** [zed-industries/create-gpui-app#20]
create-gpui-app --name my-app

thread 'main' panicked at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/create-gpui-app-0.1.2/src/main.rs:65:60:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by blacktop** [comment]
@wzzc-dev did you figure out why this was happening?

**Comment by wzzc-dev** [comment]
> @wzzc-dev did you figure out why this was happening?你弄清楚为什么会这样吗？

the latest version no longer has this problem, this issue explains why. https://github.com/zed-industries/create-gpui-app/issues/19

**Comment by wzzc-dev** [comment]
> @wzzc-dev did you figure out why this was happening?你弄清楚为什么会这样吗？

the latest version no longer has this problem, this issue explains why. https://github.com/zed-industries/create-gpui-app/issues/19 @blacktop
